services:
  nginx:
    image: jonasal/nginx-certbot
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx:/etc/nginx/user_conf.d:ro
    - ./letsencrypt:/etc/letsencrypt
    - ./emr:/www/emr:ro
    environment:
      CERTBOT_EMAIL: ilya@beda.software
